filebeat.inputs:
  - type: log
    paths:
      - /home/ubuntu/shared-logs/*.log   # Path to the logs in the shared folder
    processors:
      - add_docker_metadata: ~           # Adds Docker metadata if required
      - decode_json_fields:
          fields: ["message"]            # Decodes JSON logs in the "message" field

output.logstash:
  hosts: ["logstash:5044"]             # Ensure Filebeat sends logs to Logstash

